# Generated by Django 4.1.5 on 2023-02-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.CharField(max_length=30)),
                ('instagram', models.CharField(max_length=15)),
                ('facebook', models.CharField(max_length=18)),
            ],
        ),
    ]
